[package]
name = "creamy-engine-wasmtime-impl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
creamy-engine-core.workspace = true
thiserror.workspace = true
tracing.workspace = true
wasmtime = { version = "47.0.2", default-features = false, features = [
    "runtime",
    "cranelift",

    # debug features
    "demangle",
    "addr2line",
    "coredump",
    "debug-builtins",
] }
