[package]
name = "creamy-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
cbus-core.workspace = true
thiserror.workspace = true
rlsf = "0.2.3"
spin = "0.12.3"

[build-dependencies]
creamy-libgen-rs.workspace = true
