[package]
name = "creamy-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
cbus-core.workspace = true
thiserror.workspace = true
rlsf = "0.2.2"
spin = "0.12.2"
bit-set = "0.11.1"

[build-dependencies]
creamy-libgen-rs = { workspace = true, features = ["sdk_internal_use"] }
creamy-xmlc.workspace = true
