[package]
name = "creamy-wasmtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
creamy-engine-core.workspace = true
thiserror.workspace = true
tracing.workspace = true
wasmtime = { version = "48.0.1", default-features = false, features = [
    "runtime",
    "cranelift",
    "pooling-allocator",

    # debug features
    "demangle",
    "addr2line",
    "coredump",
    "debug-builtins",
] }
