[package]
name = "creamy-engine-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
creamy-devkit = { workspace = true, features = ["read"] }
serde.workspace = true
cbus.workspace = true
creamy-phf.workspace = true
tracing = "0.1.44"
