
[package]
id = "org.creamy.ping_printer"
name = "ping_printer"
version = "0.1.0"
description = "Plugin example"
repository = "https://github.com/purelace/creamy"
authors = [""]

# [core]
# path = ""
# runtime = ""

# [[protocols]]
# name = "compositor.wm"
# version = "0.1"
# group = 1 # optional
