[package]
name = "cbus-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
as-guard.workspace = true
static_assertions.workspace = true
downcast-rs.workspace = true
bitflags.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
