[package]
id = "org.creamy.ping"
name = "ping"
version = "0.1.0"
description = "Plugin example"
repository = "https://github.com/purelace/creamy"
authors = [ "selrisu <myirisuchan@gmail.com>" ]

[core]
path = "core.wasm"
runtime = "wasm"

[protocols]
ping = { version = "1.0", groups = [ "messages" ] }
