[package]
name = "creamy-xmlc"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
creamy-utils.workspace = true
thiserror.workspace = true
binrw.workspace = true
as-guard.workspace = true
roxmltree.workspace = true
strum.workspace = true
semver.workspace = true
downcast-rs.workspace = true
smol_str = "0.3.6"

termtree = { version = "1.0.0" }
owo-colors = { version = "4.4.0" }
miette = { version = "7.6.0", features = [ "fancy", "syntect-highlighter" ] }

[dev-dependencies]
pretty_assertions = "1.4.1"

[features]
compile = []
