[package]
name = "creamy-xmlc"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
creamy-utils.workspace = true
thiserror.workspace = true
binrw.workspace = true
as-guard.workspace = true
roxmltree.workspace = true
strum.workspace = true
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"] }
semver.workspace = true

termtree = "1.0.0"
owo-colors = "4.4.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
