[package]
name = "shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
creamy.workspace = true
creamy-wasmtime.workspace = true
creamy-async-loader.workspace = true
tracing-subscriber.workspace = true

tokio = "1.53.1"

[build-dependencies]
creamy-libgen-rs.workspace = true
creamy-devkit.workspace = true
