[package]
name = "creamy-devkit"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
read = []
write = []
compile = []

[dependencies]
creamy-xmlc = { workspace = true, features=["compile"]}
creamy-manifest.workspace = true
thiserror.workspace = true
binrw.workspace = true
semver.workspace = true
fs-err = { version = "3.3.1", features = ["debug"] }

[dev-dependencies]
creamy-template.workspace = true
tempfile.workspace = true

[[test]]
name = "compile"
required-features = ["read", "write", "compile"]

[[test]]
name = "edge_cases"
required-features = ["read", "write", "compile"]

[[test]]
name = "errors"
required-features = ["read", "write", "compile"]
