[package]
name = "creamy-devkit"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
read = []
write = []

[dependencies]
creamy-utils.workspace = true
creamy-xmlc.workspace = true
creamy-manifest.workspace = true
thiserror.workspace = true
binrw.workspace = true
semver.workspace = true
fs-err = { version = "3.3.1", features = ["debug"] }

[dev-dependencies]
creamy-template.workspace = true
tempfile.workspace = true
